services:
  nextjs-app:
    build:
      context: .
      secrets:
        - dotenv
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
    env_file:
      - .env
    restart: always

secrets:
  dotenv:
    file: .env
